version: '3.8'
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server/app:/app/app
    env_file: .env 

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # The init.conf will be changed with ssl. conf once we have ssl
      - ./nginx/init.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

