version: '3.8'

services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        # Replace with your own domain name
        VITE_BACKEND_URL: "https://api.sirshak.tech"
    ports:
      - "80:80"
    volumes:
      - ./front/src:/app/src
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server/app:/app/app
    environment:
      - VARIABLE_NAME=value # Example of setting environment variable

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # The init.conf must be replaced by ssl.conf after installing the SSL certificate 
      - ./nginx:/etc/nginx/init.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    # Replace with your own domain name and email
    command: certonly --webroot --webroot-path=/var/www/certbot --email boharasirshak101@gmail.com --agree-tos --no-eff-email -d sirshak.tech -d www.sirshak.tech -d api.sirshak.tech --manual-public-ip-logging-ok
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx
